### ISSUE TITLE
Cannot differentiate IngressClass (when using two instances)

### ISSUE THREAD

**Issue by MrChausson** [STRRL/cloudflare-tunnel-ingress-controller#185]
Hello,

I have two instances of ingress controller, each one is in its own namespace. I have to do this because I wanna create a Tunnel in another account than mine.

Here are my two values.yaml:
```
cloudflare:
  apiToken: hidden
  accountId: hidden
  tunnelName: zhcted-tunnel-landjob
  replicaCount: 1
ingressClass:
  name: landjob-app
```
```
cloudflare:
  apiToken: hidden
  accountId: hidden
  tunnelName: zhcted-tunnel
replicaCount: 1
ingressClass:
  name: chausson-services
```

I have three ingress with those ingress classes:

![Image](https://github.com/user-attachments/assets/ea1a39cd-15e7-4d0d-b2ab-87a70cd5dd96)

But in reality it creates those entries in both tunnels:

![Image](https://github.com/user-attachments/assets/5d91a8c1-2def-4bee-9245-d8be9cabacec)

![Image](https://github.com/user-attachments/assets/f172f82d-816f-443b-8fc9-ed440ae1765f)

**Comment by MrChausson** [comment]
Alright for those who come accross this error:
- You have to use a different `ingressClass.controllerValue` for each instance.

Here is what my values.yaml file looks like:

```yaml
cloudflare:
  apiToken: hidden
  accountId: hidden
  tunnelName: zhcted-tunnel-landjob
  replicaCount: 1
ingressClass:
  name: landjob-app
  controllerValue: strrl.dev/cloudflare-tunnel-ingress-controller-landjob-app
```
Then it works fine with two tunnels !
