### ISSUE TITLE
How to add ingress to the apex domain?

### ISSUE THREAD

**Issue by anatoly314** [STRRL/cloudflare-tunnel-ingress-controller#192]
Hi, first of all thank you for this controller, it was very straightforward to configure it and use, except one small issue. Maybe someone will be able to help me with that?

TL;DR, it work great for all subdomains, like test.anatoly.dev, www.anatoly.dev, but I couldn't make it work for the apex domain: https://anatoly.dev, I get DNS_PROBE_FINISHED_NXDOMAIN

Right now my ingress configuration as follow:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anatoly-dev-cloudflare-tunnel-ingress
  namespace: anatoly-dev
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: "anatoly.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: anatoly-dev
                port:
                  number: 80
```

And this doesn't work. It successfully created DNS record but I have this notification on it: 
> CNAME records normally can not be on the zone apex. We use CNAME flattening to make it possible. [Learn more](https://developers.cloudflare.com/dns/additional-options/cname-flattening/).

As far as I understood CNAME flattering already turned on for me, following this manual: https://developers.cloudflare.com/dns/cname-flattening/set-up-cname-flattening/
> CNAME flattening occurs by default for all plans when your domain uses a CNAME record for its zone apex (example.com, meaning the record Name is set to @).

And if I understood correctly I indeed use CNAME record for my zone apex:

![Image](https://github.com/user-attachments/assets/cca53c3d-51fc-48ce-a22b-289eb19fdad8)

When I change in Ingress host to:  test.anatoly.dev, everything is work. 

If someone can advise me what am I doing wrong?

**Comment by anatoly314** [comment]
Sorry guys, but it's still magic for me. Somehow it started to work for me with apex tunnel, i.e. https://anatoly.dev now redirects, but https://www.anatoly.dev doesn't work. CNAME was successfully created and this is my Ingress configuration:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anatoly-dev-cloudflare-tunnel-ingress
  namespace: anatoly-dev
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: "anatoly.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: anatoly-dev
                port:
                  number: 80
    - host: "www.anatoly.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: anatoly-dev
                port:
                  number: 80
```

what I'm doing wrong?
