### ISSUE TITLE
关于 cloudflare-tunnel-ingress-controller 使用问题

### ISSUE THREAD

**Issue by besscroft** [STRRL/cloudflare-tunnel-ingress-controller#64]
### 问题描述

您好，打扰一下，有一些使用上的问题想请教一下。
目前程序是运行正常的，且 tunnel 所有的 pod 都在控制平面上：

![image](https://github.com/STRRL/cloudflare-tunnel-ingress-controller/assets/33775809/8b5b10c6-1f2f-4a14-a33e-ef5449493e3c)

![image](https://github.com/STRRL/cloudflare-tunnel-ingress-controller/assets/33775809/4851ddbc-4362-439f-8cba-7e1045dc91fa)

Ingress 也运行正常，目前 kubesphere 面板能够通过域名正常访问：

![image](https://github.com/STRRL/cloudflare-tunnel-ingress-controller/assets/33775809/3ea45260-bbfc-4eb2-a5fc-8b23e4324284)

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: dashboard-via-cf-tunnel
  namespace: kubesphere-system
  finalizers:
    - strrl.dev/cloudflare-tunnel-ingress-controller-controlled
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: kube.besscroft.com
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: ks-console
                port:
                  number: 80
```

但是现在，我想给部署的应用服务也配置域名访问。通过查阅文档得知，是允许一条隧道配置多个域名，并分配给不同的 Service 的。
https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/routing-to-tunnel/
所以我尝试编写了如下 yaml：

```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: api-via-cf-tunnel
  namespace: opensource
  annotations:
    kubesphere.io/creator: admin
spec:
  rules:
    - host: api.besscroft.com
      http:
        paths:
          - path: /@api
            pathType: Prefix
            backend:
              service:
                name: diyfile
                port:
                  number: 8080
    - host: api.besscroft.com
      http:
        paths:
          - path: /@fast-api
            pathType: Prefix
            backend:
              service:
                name: heming-fast
                port:
                  number: 8080
```

执行后 cloudflare-tunnel-ingress-controller 和 controlled-cloudflared-connector 均没有新增任何日志，同时 cloudflare 控制台的 Public hostnames 也没有任何新增的内容，正常情况下应该会出现一条数据的：

![image](https://github.com/STRRL/cloudflare-tunnel-ingress-controller/assets/33775809/f73a7fc2-e3b4-45fa-b134-cda82f42f641)

### 集群信息

应用服务被调度至 node 节点上，每个节点间通过 Kilo（基于 WireGuard），集群间网络是正常通信的。

![image](https://github.com/STRRL/cloudflare-tunnel-ingress-controller/assets/33775809/7bea1403-d6dc-46e8-ae52-09a0a2c02c02)

```
操作系统版本: Debian GNU/Linux 11 (bullseye)
操作系统类型: Linux
内核版本: 5.10.0-26-arm64
容器运行时: containerd://1.7.7-k3s1.27
kubelet 版本: v1.27.8+k3s2
kube-proxy 版本: v1.27.8+k3s2
系统架构: ARM64
```

集群网络：

![image](https://github.com/STRRL/cloudflare-tunnel-ingress-controller/assets/33775809/f98d38c4-4739-4a18-a878-6c3016a5bf30)

应用服务调度信息：

![image](https://github.com/STRRL/cloudflare-tunnel-ingress-controller/assets/33775809/ec05417c-c8be-4ec5-a800-ab6e85025a29)

以及 Service 信息：

![image](https://github.com/STRRL/cloudflare-tunnel-ingress-controller/assets/33775809/e0289e71-8a2f-4266-af46-a3bf5dce7627)

感谢您能看到这里，我不确定是不能这样用，还是我配置错误。
谢谢！
