### ISSUE TITLE
Duplicate records repeatedly added to Ingress.status.loadBalancer.ingress

### ISSUE THREAD

**Issue by giovannimatina** [STRRL/cloudflare-tunnel-ingress-controller#88]
Since I updated the controller to version 0.0.10, I've noticed an anomalous behavior. Every time the controller iterates, new duplicate records are added to the ingress list within the loadBalancer field of the status. This behavior is leading to a continuous accumulation of duplicates, compromising the integrity and usefulness of the status.

Example of the issue:

```
status:
  loadBalancer:
    ingress:
    - hostname: example-uuid.cfargotunnel.com
      ports:
      - port: 443
        protocol: TCP
    - hostname: example-uuid.cfargotunnel.com
      ports:
      - port: 443
        protocol: TCP
    - hostname: example-uuid.cfargotunnel.com
      ports:
      - port: 443
        protocol: TCP
...
```
