### ISSUE TITLE
cloudflared values don't appear to be respected

### ISSUE THREAD

**Issue by evanrich** [STRRL/cloudflare-tunnel-ingress-controller#99]
I've had the following in my values file for weeks:

```
cloudflared:
  image:
    repository: cloudflare/cloudflared
    pullPolicy: IfNotPresent
    tag: 2024.6.1
```
yet argocd never updates the cloudflared container, it says everything is up-to-date, but my cloudflared image is still on 2024.3.0.  I had to manually update the deployment to 2024.6.1.  I don't think it's an argocd issue because argo shows the chart + values are in the correct state, meaning the chart doesn't see the values, and the 50 other charts I have deployed in it all work fine when updating images.  here are my values.yaml contents:

```
cloudflare:
  secretRef:
    name: cloudflare-tunnel-credentials
    accountIDKey: account_id
    tunnelNameKey: tunnel_name
    apiTokenKey: api_token

ingressClass:
  name: cloudflare-tunnel
  controllerValue: strrl.dev/cloudflare-tunnel-ingress-controller
  isDefaultClass: false

replicaCount: 2

image:
  repository: ghcr.io/strrl/cloudflare-tunnel-ingress-controller
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 30m
     memory: 64Mi

cloudflared:
  image:
    repository: cloudflare/cloudflared
    pullPolicy: IfNotPresent
    tag: 2024.6.1
```
